.\"
.\" Copyright (C) 2020  Esote
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU Affero General Public License as published
.\" by the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU Affero General Public License for more details.
.\"
.\" You should have received a copy of the GNU Affero General Public License
.\" along with this program.  If not, see <https://www.gnu.org/licenses/>.
.\"
.Dd $Mdocdate: January 30 2019 $
.Dt FILESRV 1
.Os
.Sh NAME
.Nm filesrv
.Nd filesystem web server
.Sh SYNOPSIS
.Nm filesrv
.Op Fl d
.Op Fl p Ar port
.Op Fl t Ar timeout
.Op Fl u Ar user
dir
.Sh DESCRIPTION
.Nm filesrv
is a filesystem web server.
It responds with directory listings or file contents based on the request path.
The
.Fl d
option daemonizes the process.
The
.Fl p
option specifies the listening port, otherwise 8080 by default.
.Fl t
option specifies the read and write timeout, otherwise 10 seconds by default.
.Pp
The
.Fl u
option causes
.Nm filesrv
to drop privileges to the specified user.
This is only available when
.Nm filesrv
is run as root.
It is useful when listening on a privileged lower port without needing
persistent root access.
.Sh AUTHORS
.Nm filesrv
was written by
.An Esote .
.Sh COPYRIGHT
Copyright
.Pq c
2020 Esote.
There is NO warranty.
You may redistribute this software under the terms of the GNU Affero General
Public License.
For more information, see the
.Pa LICENSE
file.
